services:
  flaskapp:
    image: fernandoribeiro357/python-flaskapp:latest
    # build:
    #  context: .
      # dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=True
      - JWT_SECRET=c04575fffdd07e3b5f6dfc9401bbf780c20eed9c
      - SECRET_KEY=Wievievae5fa3eig5eaWaichooQuah4k
      - APP_URL=http://localhost:8000
      - MONGO_URL=mongodb://root:root-passwd@mongo-server:27017/
    volumes:
      - ./flaskapp:/opt/app

  mongo-server:
    image: "mongo:latest"
    # restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=pessoa
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root-passwd
    volumes:
      - ./users.js:/docker-entrypoint-initdb.d/users.js:ro
      
  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root-passwd
      - ME_CONFIG_MONGODB_URL=mongodb://root:root-passwd@mongo-server:27017/
      - ME_CONFIG_BASICAUTH=false
      

# volumes:
#   mongodb_teste: {}
