services:
  flaskapp:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./flaskapp/.env
    volumes:
      - ./flaskapp:/opt/app

  mongo-server:
    image: "mongo:latest"
    # restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - ./users.js:/docker-entrypoint-initdb.d/users.js:ro
      
  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
  
  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./openapi:/tmp
    environment:
      SWAGGER_JSON: /tmp/flaskapp_openapi.yaml
      

volumes:
  mongodb_teste: {}
