services:
  auth_service:
    image: "auth_service"
    ports:
      - 5000:5000
    volumes:
      - "$PWD:/app"

  mongo-server:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "mongodb:/data/db"
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      #ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongo-server:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongodb: {}
