services:
  flaskapp:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    # env_file:
    #   - ./flaskapp/.env
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=True
      - JWT_SECRET="flaskapp-jwt-secret"
      - JWT_REFRESH_SECRET="flaskapp-jwt-refresh-secret"
      - APP_URL=http://localhost:8000
      - MONGO_ROOT_USERNAME=root
      - MONGO_ROOT_PASSWORD=root-passwd
      - MONGO_URL="mongodb://root:root-passwd@mongo-server:27017/"
    volumes:
      - ./flaskapp:/opt/app

  mongo-server:
    image: "mongo:latest"
    # restart: always
    ports:
      - 27017:27017
    # env_file:
    #   - .env
    environment:
      - MONGO_INITDB_DATABASE=pessoa
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root-passwd
    volumes:
      - ./users.js:/docker-entrypoint-initdb.d/users.js:ro
      
  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    # env_file:
    #   - .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root-passwd
      - ME_CONFIG_MONGODB_URL="mongodb://root:root-passwd@mongo-server:27017/"
      - ME_CONFIG_BASICAUTH=false
  
  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./openapi:/tmp
    environment:
      SWAGGER_JSON: /tmp/openapi.yml
      

volumes:
  mongodb_teste: {}
