services:
  flaskapp:
    build:
      context: .
      dockerfile: dev.Dockerfile

    ports:
      - 8000:8000
    env_file:
      - ./flaskapp/.env
    volumes:
      - ./flaskapp:/opt/app

  mongo-server:
    image: "mongo:latest"

    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=3o5bpq
      - MONGO_INITDB_DATABASE=pessoa
    # entrypoint: users.json
    volumes:
      - "mongodb:/data/db"
      
  mongo-express:
    image: mongo-express

    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=3o5bpq
      - ME_CONFIG_MONGODB_URL=mongodb://mongoadmin:3o5bpq@mongo-server:27017/
      - ME_CONFIG_BASICAUTH=false
      

volumes:
  mongodb: {}
