"openapi": "3.0.0"
"info":
  "title": "flaskapp"
"paths":
  "/api/v1/auth":
    "post":
      "description": "Autenticação do usuário. Retorna o refresh_token."
      "parameters": []
      "requestBody":
        "description": "Autenticação do usuário. Retorna o refresh_token."
        "content":
          "application/json":
            "schema":
              "type": "string"
        "required": true
      "responses":
        '200':
          "description": "Successful operation"
          "content":
            "application/json":
              {"ACK": true,"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZmVybmFuZG8iLCJleHAiOjE3MjIyMjk5NzF9.WWv4kAx2YDA-h_4DtBfxzhAiIJ9AnVmWDl_cPofUZdI"}
        '400':
          "description": "Invalid input"
      "summary": "auth_refresh_token"
      "operationId": "auth_refresh_token"
      "tags":
        - "develop"
  "/api/v1/get_profile_data":
    "get":
      "description": "Busca o perfil do usuário logado, solicitando um access_token
        antes da requisição."
      "parameters": []
      "responses": {}
      "summary": "get_profile_data"
      "operationId": "get_profile_data"
      "tags":
        - "develop"
  "/api/v1/get_profiles":
    "get":
      "description": "Busca todos os perfis não excluídos (created_at: None),
        solicitando um access_token antes da requisição.<p></p>


        Somente os usuários com perfil administrativo (profile:
        sysadmin) podem executar essa ação."
      "parameters": []
      "responses": {}
      "summary": "get_profiles"
      "operationId": "get_profiles"
      "tags":
        - "develop"
  "/api/v1/insert_profile":
    "post":
      "description": "Insere um novo perfi de usuário (profile: user), solicitando um
        access_token antes da requisição.<p></p>


        Somente os usuários com perfil administrativo (profile:
        sysadmin) podem executar essa ação."
      "parameters": []
      "responses": {}
      "summary": "insert_profile"
      "operationId": "insert_profile"
      "tags":
        - "develop"
  "/api/v1/update_profile":
    "put":
      "description": "Atualiza os dados de um perfil (created_at: None), solicitando
        um access_token antes da requisição.<p></p>


        Somente os usuários com perfil administrativo (profile:
        sysadmin) ou o dono do perfil a ser alterado podem executar essa
        ação.<p></p>


        O campo 'username' não pode ser alterado.<p></p>


        Somente os usuários com perfil administrativo podem alterar o
        campo 'profile', exceto o seu próprio perfil."
      "parameters": []
      "responses": {}
      "summary": "update_profile"
      "operationId": "update_profile"
      "tags":
        - "develop"
  "/api/v1/delete_profile":
    "delete":
      "description": "Exclui um perfil (deleted_at: datetime.utcnow()), solicitando um
        access_token antes da requisição.<p></p>


        Somente os usuários com perfil administrativo (profile:
        sysadmin) podem executar essa ação.<p></p>


        Um usuário não pode excluir o próprio perfil."
      "parameters": []
      "responses": {}        
      "summary": "delete_profile"
      "operationId": "delete_profile"
      "tags":
        - "develop"
  "/api/v1/auth/get_access_token":
    "get":
      "description": "Solicita um access_token, fornecendo um refresh_token, para
        realizar as operações CRUD na API."
      "parameters": []
      "responses":        
      "summary": "auth_access_token"
      "operationId": "auth_access_token"
      "tags":
        - "develop"
"tags": []
"servers":
  - "url": "http://172.18.0.4:8000"
  - "url": "http://localhost:8000"
  - "url": "http://flaskapp:8000"
"components":
  "schemas": {}
