"openapi": "3.0.0"
"info":
  "title": "flaskapp"
"paths":
  "/api/v1/auth":
    "post":
      "description": "Autenticação do usuário. Retorna o refresh_token."
      "parameters": []
      "responses": {}
      "summary": "auth_refresh_token"
      "operationId": "auth_refresh_token"
      "tags":
        - "develop"
  "/api/v1/auth/get_access_token":
    "get":
      "description": "Solicita um access_token, fornecendo um refresh_token, para
        realizar as operações CRUD na API."
      "parameters": []
      "responses": {}
      "summary": "auth_access_token"
      "operationId": "auth_access_token"
      "tags":
        - "develop"
"tags": []
"servers":
  - "url": "http://localhost"
"components":
  "schemas": {}
