openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:8000
paths:
  /api/v1/auth:
    post:
      responses:
        '200':
          description: OK
      requestBody:
        description: Autenticação do usuário. Retorna o refresh_token.
        content:
          application/json:
            schema:
              type: string
        required: true

